before:
  hooks:
    - go mod download
builds:
  - id: kubectl-flame
    main: ./cli/main.go
    binary: kubectl-flame
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    goarm: [6, 7]
    ldflags: |
      -X github.com/VerizonMedia/kubectl-flame/cli/cmd/version.semver={{ .Tag }}
      -X github.com/VerizonMedia/kubectl-flame/cli/cmd/version.date={{ .Date }}
      -X github.com/VerizonMedia/kubectl-flame/cli/cmd/version.commit={{ .Commit }}
archives:
  - id: kubectl-flame-archive
    name_template: |
      kubectl-flame_{{ .Tag }}_{{ .Os }}_{{ .Arch -}}
      {{- with .Arm -}}
        {{- if (eq . "6") -}}hf
        {{- else -}}v{{- . -}}
        {{- end -}}
      {{- end -}}
    builds:
      - kubectl-flame
    replacements:
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files: ["LICENSE"]
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256